spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/todo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: ${KEY_VAULT_URI:}
      credential:
        managed-identity-enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      platform: postgresql
      continue-on-error: true
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      separator: ;

server:
  port: 8080
