-- Insert sample todo items
INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Complete project documentation', 'Write comprehensive documentation for the Todo API project', 0, 5, CURRENT_TIMESTAMP + INTERVAL '7 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Fix UI bugs', 'Address the UI bugs reported in the frontend application', 0, 8, CURRENT_TIMESTAMP + INTERVAL '2 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Review pull requests', 'Review and provide feedback on pending pull requests', 1, 7, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day');

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Prepare for demo', 'Prepare slides and setup environment for the upcoming demo', 0, 9, CURRENT_TIMESTAMP + INTERVAL '3 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Update dependencies', 'Update project dependencies to the latest versions', 1, 4, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '3 days');

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Implement search functionality', 'Add search functionality to the application', 0, 6, CURRENT_TIMESTAMP + INTERVAL '5 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Write unit tests', 'Increase test coverage with additional unit tests', 0, 7, CURRENT_TIMESTAMP + INTERVAL '4 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Deploy to production', 'Deploy the latest changes to the production environment', 0, 10, CURRENT_TIMESTAMP + INTERVAL '10 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Create user documentation', 'Write user guides and API documentation', 0, 5, CURRENT_TIMESTAMP + INTERVAL '8 days', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Code review', 'Perform code review for the recent changes', 1, 6, CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 days');
