# AWS S3 Configuration
aws.accessKeyId=${AWS_ACCESS_KEY_ID:}
aws.secretKey=${AWS_SECRET_KEY:}
aws.region=us-east-1
aws.s3.bucket=your-bucket-name

# Application name
spring.application.name=assets-manager-worker

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
<<<<<<< HEAD
spring.rabbitmq.username=guest
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/assets_manager
spring.datasource.username=postgres
spring.datasource.password=${DATASOURCE_PASSWORD}
=======
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=guest

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/assets_manager
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=postgres
>>>>>>> refs/remotes/origin/main
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
